Traceback (most recent call last):
  File "/usr/share/miniconda/envs/hatp23b/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/hatp23b/lib/python3.9/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/hatp23b/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/hatp23b/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/hatp23b/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/hatp23b/lib/python3.9/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/hatp23b/lib/python3.9/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/share/miniconda/envs/hatp23b/lib/python3.9/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
base_dir = "data/retrieval_tspec"

# Retrievals with lowest and highest log-evidences
fpaths_dict_extrema = {
    "K (clear)": f"{base_dir}/HATP23_E1_NoHet_FitP0_NoClouds_NoHaze_NofitR0_K",  # Worst
    "TiO (clear)": f"{base_dir}/HATP23_E1_NoHet_FitP0_NoClouds_NoHaze_NofitR0_TiO",  # Best
}
data_dict_extrema = {
    model_name: {
        "tspec": ascii.read(f"{model_dir}/retr_model.txt"),
        "tspec_sampled": ascii.read(
            f"{model_dir}/retr_model_sampled_Magellan_IMACS.txt"
        ),
        "retrieval": utils.load_pickle(f"{model_dir}/retrieval.pkl"),
    }
    for (model_name, model_dir) in fpaths_dict_extrema.items()
}

# Additional retreivals to compare overall shape
fpaths_dict = {
    "Na+K (clear)": f"{base_dir}/HATP23_E1_NoHet_FitP0_NoClouds_NoHaze_NofitR0_Na_K",
    "Na+K (cloud)": f"{base_dir}/HATP23_E1_NoHet_FitP0_Clouds_NoHaze_NofitR0_Na_K",
    "Na+K (haze)": f"{base_dir}/HATP23_E1_NoHet_FitP0_NoClouds_Haze_NofitR0_Na_K",
    "Na+K (spot)": f"{base_dir}/HATP23_E1_Het_FitP0_NoClouds_NoHaze_NofitR0_Na_K",
}
data_dict = {
    model_name: {
        "tspec": ascii.read(f"{model_dir}/retr_model.txt"),
        "tspec_sampled": ascii.read(
            f"{model_dir}/retr_model_sampled_Magellan_IMACS.txt"
        ),
        "retrieval": utils.load_pickle(f"{model_dir}/retrieval.pkl"),
    }
    for (model_name, model_dir) in fpaths_dict.items()
}

# Instrument data
instrument_dict = {
    "Magellan_IMACS": {
        "plot_kwargs": {
            "c": "w",
            "mec": "k",
            "fmt": "o",
            "ecolor": "k",
            "label": "Magellan/IMACS",
            "zorder": 10,
        },
        "data": ascii.read(f"{base_dir}/instrument/retr_Magellan_IMACS.txt"),
    }
}
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-3-8b9d73a50a3a>[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m     [0;34m"TiO (clear)"[0m[0;34m:[0m [0;34mf"{base_dir}/HATP23_E1_NoHet_FitP0_NoClouds_NoHaze_NofitR0_TiO"[0m[0;34m,[0m  [0;31m# Best[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m }
[0;32m----> 8[0;31m data_dict_extrema = {
[0m[1;32m      9[0m     model_name: {
[1;32m     10[0m         [0;34m"tspec"[0m[0;34m:[0m [0mascii[0m[0;34m.[0m[0mread[0m[0;34m([0m[0;34mf"{model_dir}/retr_model.txt"[0m[0;34m)[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m<ipython-input-3-8b9d73a50a3a>[0m in [0;36m<dictcomp>[0;34m(.0)[0m
[1;32m     12[0m             [0;34mf"{model_dir}/retr_model_sampled_Magellan_IMACS.txt"[0m[0;34m[0m[0;34m[0m[0m
[1;32m     13[0m         ),
[0;32m---> 14[0;31m         [0;34m"retrieval"[0m[0;34m:[0m [0mutils[0m[0;34m.[0m[0mload_pickle[0m[0;34m([0m[0;34mf"{model_dir}/retrieval.pkl"[0m[0;34m)[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     15[0m     }
[1;32m     16[0m     [0;32mfor[0m [0;34m([0m[0mmodel_name[0m[0;34m,[0m [0mmodel_dir[0m[0;34m)[0m [0;32min[0m [0mfpaths_dict_extrema[0m[0;34m.[0m[0mitems[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/work/HAT-P-23b/HAT-P-23b/notebooks/utils.py[0m in [0;36mload_pickle[0;34m(fpath)[0m
[1;32m    147[0m [0;34m[0m[0m
[1;32m    148[0m [0;32mdef[0m [0mload_pickle[0m[0;34m([0m[0mfpath[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 149[0;31m     [0;32mwith[0m [0mopen[0m[0;34m([0m[0mfpath[0m[0;34m,[0m [0;34m"rb"[0m[0;34m)[0m [0;32mas[0m [0mf[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    150[0m         [0mdata[0m [0;34m=[0m [0mpickle[0m[0;34m.[0m[0mload[0m[0;34m([0m[0mf[0m[0;34m,[0m [0mencoding[0m[0;34m=[0m[0;34m"latin"[0m[0;34m)[0m  [0;31m# Python 2 -> 3[0m[0;34m[0m[0;34m[0m[0m
[1;32m    151[0m     [0;32mreturn[0m [0mdata[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'data/retrieval_tspec/HATP23_E1_NoHet_FitP0_NoClouds_NoHaze_NofitR0_K/retrieval.pkl'
FileNotFoundError: [Errno 2] No such file or directory: 'data/retrieval_tspec/HATP23_E1_NoHet_FitP0_NoClouds_NoHaze_NofitR0_K/retrieval.pkl'

