Traceback (most recent call last):
  File "/usr/share/miniconda/envs/hatp23b/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/hatp23b/lib/python3.9/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/hatp23b/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/hatp23b/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/hatp23b/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/hatp23b/lib/python3.9/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/hatp23b/lib/python3.9/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/share/miniconda/envs/hatp23b/lib/python3.9/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
base_dir_fixed_R0 = "data/retrieval_evidence/spot_lower_fixed_R0"
(
    df_Delta_lnZ_fixed,
    df_Delta_lnZ_err_fixed,
    species_min_fixed,
    model_min_fixed,
    data_dict_fixed,
) = utils.get_evidences(base_dir_fixed_R0)

base_dir_fit_R0 = "data/retrieval_evidence/spot_lower_fit_R0"
(
    df_Delta_lnZ_fit,
    df_Delta_lnZ_err_fit,
    species_min_fit,
    model_min_fit,
    data_dict_fit,
) = utils.get_evidences(base_dir_fit_R0)

print("Fixed R0")
print(f"Minimul log-evidence: ({species_min_fixed}, {model_min_fixed})")
display(df_Delta_lnZ_fixed)

print("\nFit R0")
print(f"Minimul log-evidence: ({species_min_fit}, {model_min_fit})")
display(df_Delta_lnZ_fit)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-3-47c0121b74da>[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m     [0mmodel_min_fixed[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m     [0mdata_dict_fixed[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 8[0;31m ) = utils.get_evidences(base_dir_fixed_R0)
[0m[1;32m      9[0m [0;34m[0m[0m
[1;32m     10[0m [0mbase_dir_fit_R0[0m [0;34m=[0m [0;34m"data/retrieval_evidence/spot_lower_fit_R0"[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/work/HAT-P-23b/HAT-P-23b/notebooks/utils.py[0m in [0;36mget_evidences[0;34m(base_dir)[0m
[1;32m     74[0m     }
[1;32m     75[0m [0;34m[0m[0m
[0;32m---> 76[0;31m     data_dict = {
[0m[1;32m     77[0m         sp: {
[1;32m     78[0m             model_name: load_pickle(

[0;32m~/work/HAT-P-23b/HAT-P-23b/notebooks/utils.py[0m in [0;36m<dictcomp>[0;34m(.0)[0m
[1;32m     75[0m [0;34m[0m[0m
[1;32m     76[0m     data_dict = {
[0;32m---> 77[0;31m         sp: {
[0m[1;32m     78[0m             model_name: load_pickle(
[1;32m     79[0m                 [0;34mf"{base_dir}/HATP23_E1_{model_id}_{sp}/retrieval.pkl"[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/work/HAT-P-23b/HAT-P-23b/notebooks/utils.py[0m in [0;36m<dictcomp>[0;34m(.0)[0m
[1;32m     76[0m     data_dict = {
[1;32m     77[0m         sp: {
[0;32m---> 78[0;31m             model_name: load_pickle(
[0m[1;32m     79[0m                 [0;34mf"{base_dir}/HATP23_E1_{model_id}_{sp}/retrieval.pkl"[0m[0;34m[0m[0;34m[0m[0m
[1;32m     80[0m             )

[0;32m~/work/HAT-P-23b/HAT-P-23b/notebooks/utils.py[0m in [0;36mload_pickle[0;34m(fpath)[0m
[1;32m    147[0m [0;34m[0m[0m
[1;32m    148[0m [0;32mdef[0m [0mload_pickle[0m[0;34m([0m[0mfpath[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 149[0;31m     [0;32mwith[0m [0mopen[0m[0;34m([0m[0mfpath[0m[0;34m,[0m [0;34m"rb"[0m[0;34m)[0m [0;32mas[0m [0mf[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    150[0m         [0mdata[0m [0;34m=[0m [0mpickle[0m[0;34m.[0m[0mload[0m[0;34m([0m[0mf[0m[0;34m,[0m [0mencoding[0m[0;34m=[0m[0;34m"latin"[0m[0;34m)[0m  [0;31m# Python 2 -> 3[0m[0;34m[0m[0;34m[0m[0m
[1;32m    151[0m     [0;32mreturn[0m [0mdata[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'data/retrieval_evidence/spot_lower_fixed_R0/HATP23_E1_NoHet_FitP0_NoClouds_NoHaze_NofitR0_Na/retrieval.pkl'
FileNotFoundError: [Errno 2] No such file or directory: 'data/retrieval_evidence/spot_lower_fixed_R0/HATP23_E1_NoHet_FitP0_NoClouds_NoHaze_NofitR0_Na/retrieval.pkl'

